In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
from google.colab import files
import math
from PIL import Image
from io import BytesIO
from PIL import Image
import urllib
from matplotlib import image
from PIL import Image, ImageOps

In [2]:
def product(x,y):
    result=np.zeros((49,63))
    for i in range(49):
        result[i,:]=x[i]*y
    return result

In [3]:
def bipolar_convertor(vector):
    res=[]
    for i in range(len(vector)):
        if vector[i]>0:
            res.append(1)
        
        if vector[i]==0:
            res.append(-1)
    return res

In [4]:
def activation_function(x):
    res=[]
    for i in range(len(x)):
        if x[i]>0:
            res.append(1)
        
        if x[i]<=0:
            res.append(-1)
    return res

In [5]:
X=np.zeros((4,49))
Y=np.zeros((4,63))
X[0,:]=np.array([1,0,0,0,0,1,1,1,1,0,1,1,0,0,1,1,0,1,0,0,1,1,1,0,1,1,1,0,1,1,1,0,1,0,0,1,1,0,1,1,1,1,1,1,0,1,1,1,0])
X[1,:]=np.array([1,0,0,1,0,0,0,1,1,0,1,0,0,1,1,1,0,1,1,0,0,1,1,0,1,1,0,0,1,1,0,0,0,0,1,1,1,1,0,0,1,0,1,1,1,1,0,0,1])
X[2,:]=np.array([1,0,0,1,0,1,1,1,1,0,0,1,0,1,1,1,0,1,1,1,0,1,1,1,0,0,1,1,1,1,1,0,1,0,0,1,1,0,0,0,0,1,1,1,1,0,0,1,0])
X[3,:]=np.array([1,0,0,1,1,0,0,1,1,0,0,1,0,1,1,1,1,0,1,1,1,1,1,0,1,0,0,1,1,1,1,0,0,1,1,1,1,0,1,0,1,1,1,1,1,1,0,0,1])
Y[0,:]=np.array([1,0,1,0,0,0,0,1,1,1,0,0,1,0,1,1,0,0,1,0,1,1,1,1,0,0,1,1,1,1,0,1,0,0,1,1,1,0,0,1,0,0,1,1,0,0,1,0,1,1,1,0,1,1,1,0,1,1,1,0,1,0,0])
Y[1,:]=np.array([1,0,0,0,1,1,0,1,1,0,1,0,0,1,1,1,1,0,0,1,0,1,1,1,0,0,1,1,1,1,1,0,1,0,0,1,0,0,1,1,0,0,1,1,0,0,0,0,1,1,1,0,0,1,0,0,1,1,1,1,0,0,1])
Y[2,:]=np.array([1,0,0,0,1,1,1,1,1,0,0,1,0,1,1,1,0,1,1,1,0,1,1,1,0,1,0,0,1,1,0,1,1,0,0,1,1,0,0,1,0,1,1,1,0,1,1,0,1,1,1,0,0,0,0,1,1,1,0,1,1,1,0])
Y[3,:]=np.array([1,0,1,0,0,1,1,1,1,1,0,1,1,1,1,1,0,0,1,0,1,1,1,0,0,1,0,1,1,1,1,0,1,0,0,1,0,0,0,1,1,1,1,1,0,1,0,0,1,1,1,1,0,0,1,0,1,1,0,1,1,0,0])

In [6]:
X[0,:]=bipolar_convertor(X[0])
X[1,:]=bipolar_convertor(X[1])
X[2,:]=bipolar_convertor(X[2])
X[3,:]=bipolar_convertor(X[3])
Y[0,:]=bipolar_convertor(Y[0])
Y[1,:]=bipolar_convertor(Y[1])
Y[2,:]=bipolar_convertor(Y[2])
Y[3,:]=bipolar_convertor(Y[3])

In [7]:
X=X.astype(int)
Y=Y.astype(int)

In [8]:
print(X)

[[ 1 -1 -1 -1 -1  1  1  1  1 -1  1  1 -1 -1  1  1 -1  1 -1 -1  1  1  1 -1
   1  1  1 -1  1  1  1 -1  1 -1 -1  1  1 -1  1  1  1  1  1  1 -1  1  1  1
  -1]
 [ 1 -1 -1  1 -1 -1 -1  1  1 -1  1 -1 -1  1  1  1 -1  1  1 -1 -1  1  1 -1
   1  1 -1 -1  1  1 -1 -1 -1 -1  1  1  1  1 -1 -1  1 -1  1  1  1  1 -1 -1
   1]
 [ 1 -1 -1  1 -1  1  1  1  1 -1 -1  1 -1  1  1  1 -1  1  1  1 -1  1  1  1
  -1 -1  1  1  1  1  1 -1  1 -1 -1  1  1 -1 -1 -1 -1  1  1  1  1 -1 -1  1
  -1]
 [ 1 -1 -1  1  1 -1 -1  1  1 -1 -1  1 -1  1  1  1  1 -1  1  1  1  1  1 -1
   1 -1 -1  1  1  1  1 -1 -1  1  1  1  1 -1  1 -1  1  1  1  1  1  1 -1 -1
   1]]


In [9]:
print(Y)

[[ 1 -1  1 -1 -1 -1 -1  1  1  1 -1 -1  1 -1  1  1 -1 -1  1 -1  1  1  1  1
  -1 -1  1  1  1  1 -1  1 -1 -1  1  1  1 -1 -1  1 -1 -1  1  1 -1 -1  1 -1
   1  1  1 -1  1  1  1 -1  1  1  1 -1  1 -1 -1]
 [ 1 -1 -1 -1  1  1 -1  1  1 -1  1 -1 -1  1  1  1  1 -1 -1  1 -1  1  1  1
  -1 -1  1  1  1  1  1 -1  1 -1 -1  1 -1 -1  1  1 -1 -1  1  1 -1 -1 -1 -1
   1  1  1 -1 -1  1 -1 -1  1  1  1  1 -1 -1  1]
 [ 1 -1 -1 -1  1  1  1  1  1 -1 -1  1 -1  1  1  1 -1  1  1  1 -1  1  1  1
  -1  1 -1 -1  1  1 -1  1  1 -1 -1  1  1 -1 -1  1 -1  1  1  1 -1  1  1 -1
   1  1  1 -1 -1 -1 -1  1  1  1 -1  1  1  1 -1]
 [ 1 -1  1 -1 -1  1  1  1  1  1 -1  1  1  1  1  1 -1 -1  1 -1  1  1  1 -1
  -1  1 -1  1  1  1  1 -1  1 -1 -1  1 -1 -1 -1  1  1  1  1  1 -1  1 -1 -1
   1  1  1  1 -1 -1  1 -1  1  1 -1  1  1 -1 -1]]


In [10]:
W_BAM=np.zeros((49,63))
for i in range(3):
    W_BAM=W_BAM+product(X[i],Y[i])

In [11]:
W_BAM=W_BAM.astype(int)
print(W_BAM)

[[ 3 -3 -1 ...  1 -1 -1]
 [-3  3  1 ... -1  1  1]
 [-3  3  1 ... -1  1  1]
 ...
 [-1  1  3 ...  1 -1 -1]
 [ 1 -1  1 ...  3  1 -3]
 [-1  1 -1 ... -3 -1  3]]


In [12]:
def noise_adder(input_vector,noise_percent):
    result=np.array(input_vector)
    for i in range(math.floor((noise_percent/100)*len(result))+1):
        random_index = random.randint(0,len(result)-1)
        if input_vector[random_index]==1:
            result[random_index]=-1
        if input_vector[random_index]==-1:
            result[random_index]=+1
    return result

In [13]:
def predict_output_BAM(input_vector1,input_vector2,input_vector3,w):
    res1=[]
    res2=[]
    res3=[]
    for j in range(w.shape[1]):
        res1.append(np.dot(input_vector1,w[:,j]))
        res2.append(np.dot(input_vector2,w[:,j]))
        res3.append(np.dot(input_vector3,w[:,j]))
        nn1=activation_function(res1)
        nn2=activation_function(res2)
        nn3=activation_function(res3)

    return nn1,nn2,nn3

In [22]:
predict1,predict2,predict3=predict_output_BAM(X[0],X[1],X[2],W_BAM)

print("output1:",predict1)
print("real output:",Y[0])
print("output2:",predict1)
print("real output:",Y[1])
print("output3:",predict1)
print("real output:",Y[2])

output1: [1, -1, 1, -1, -1, -1, -1, 1, 1, 1, -1, -1, 1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, 1, -1, -1, 1, 1, 1, 1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, -1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, -1]
real output: [ 1 -1  1 -1 -1 -1 -1  1  1  1 -1 -1  1 -1  1  1 -1 -1  1 -1  1  1  1  1
 -1 -1  1  1  1  1 -1  1 -1 -1  1  1  1 -1 -1  1 -1 -1  1  1 -1 -1  1 -1
  1  1  1 -1  1  1  1 -1  1  1  1 -1  1 -1 -1]
output2: [1, -1, 1, -1, -1, -1, -1, 1, 1, 1, -1, -1, 1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, 1, -1, -1, 1, 1, 1, 1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, -1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, -1]
real output: [ 1 -1 -1 -1  1  1 -1  1  1 -1  1 -1 -1  1  1  1  1 -1 -1  1 -1  1  1  1
 -1 -1  1  1  1  1  1 -1  1 -1 -1  1 -1 -1  1  1 -1 -1  1  1 -1 -1 -1 -1
  1  1  1 -1 -1  1 -1 -1  1  1  1  1 -1 -1  1]
output3: [1, -1, 1, -1, -1, -1, -1, 1, 1, 1, -1, -1, 1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, 1, -1, -1, 1, 1, 1, 1, -1, 1, -1, -1, 1, 1, 

In [14]:
W_inverse=W_BAM.T
print(W_inverse)
predict1,predict2,predict3=predict_output_BAM(Y[0],Y[1],Y[2],W_inverse)

print("output1:",predict1)
print("real output:",X[0])
print("output2:",predict2)
print("real output:",X[1])
print("output3:",predict3)
print("real output:",X[2])

[[ 3 -3 -3 ... -1  1 -1]
 [-3  3  3 ...  1 -1  1]
 [-1  1  1 ...  3  1 -1]
 ...
 [ 1 -1 -1 ...  1  3 -3]
 [-1  1  1 ... -1  1 -1]
 [-1  1  1 ... -1 -3  3]]
output1: [1, -1, -1, -1, -1, 1, 1, 1, 1, -1, 1, 1, -1, -1, 1, 1, -1, 1, -1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, -1]
real output: [ 1 -1 -1 -1 -1  1  1  1  1 -1  1  1 -1 -1  1  1 -1  1 -1 -1  1  1  1 -1
  1  1  1 -1  1  1  1 -1  1 -1 -1  1  1 -1  1  1  1  1  1  1 -1  1  1  1
 -1]
output2: [1, -1, -1, 1, -1, -1, -1, 1, 1, -1, 1, -1, -1, 1, 1, 1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, 1, 1, -1, -1, 1, -1, 1, 1, 1, 1, -1, -1, 1]
real output: [ 1 -1 -1  1 -1 -1 -1  1  1 -1  1 -1 -1  1  1  1 -1  1  1 -1 -1  1  1 -1
  1  1 -1 -1  1  1 -1 -1 -1 -1  1  1  1  1 -1 -1  1 -1  1  1  1  1 -1 -1
  1]
output3: [1, -1, -1, 1, -1, 1, 1, 1, 1, -1, -1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, -1, 1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, 1, 1,

In [43]:
res1=[]
res2=[]
res3=[]
res4=[]
res5=[]
res6=[]

res7=[]
res8=[]
res9=[]
res10=[]
res11=[]
res12=[]

iteration_Num=100
for i in range(iteration_Num):
    
  go_noisy_signal1_1=noise_adder(X[0],10)
  go_noisy_signal1_2=noise_adder(X[0],20)

  go_noisy_signal2_1=noise_adder(X[1],10)
  go_noisy_signal2_2=noise_adder(X[1],20)

  go_noisy_signal3_1=noise_adder(X[2],10)
  go_noisy_signal3_2=noise_adder(X[2],20)

        
  go_nn1_1,go_nn2_1,go_nn3_1=predict_output_BAM(go_noisy_signal1_1,go_noisy_signal2_1,go_noisy_signal3_1,W_BAM)
  go_nn1_2,go_nn2_2,go_nn3_2=predict_output_BAM(go_noisy_signal1_2,go_noisy_signal2_2,go_noisy_signal3_2,W_BAM)
    
  n_zeros=np.count_nonzero(abs(go_nn1_1-Y[0])==0)
  res1.append(n_zeros/63)
  n_zeros=np.count_nonzero(abs(go_nn2_1-Y[1])==0)
  res2.append(n_zeros/63)
  n_zeros=np.count_nonzero(abs(go_nn3_1-Y[2])==0)
  res3.append(n_zeros/63)

  n_zeros=np.count_nonzero(abs(go_nn1_2-Y[0])==0)
  res4.append(n_zeros/63)
  n_zeros=np.count_nonzero(abs(go_nn2_2-Y[1])==0)
  res5.append(n_zeros/63)
  n_zeros=np.count_nonzero(abs(go_nn3_2-Y[2])==0)
  res6.append(n_zeros/63)





  turn_noisy_signal1_1=noise_adder(Y[0],10)
  turn_noisy_signal1_2=noise_adder(Y[0],20)

  turn_noisy_signal2_1=noise_adder(Y[1],10)
  turn_noisy_signal2_2=noise_adder(Y[1],20)

  turn_noisy_signal3_1=noise_adder(Y[2],10)
  turn_noisy_signal3_2=noise_adder(Y[2],20)

        
  turn_nn1_1,turn_nn2_1,turn_nn3_1=predict_output_BAM(turn_noisy_signal1_1,turn_noisy_signal2_1,turn_noisy_signal3_1,W_inverse)
  turn_nn1_2,turn_nn2_2,turn_nn3_2=predict_output_BAM(turn_noisy_signal1_2,turn_noisy_signal2_2,turn_noisy_signal3_2,W_inverse)
    
  n_zeros=np.count_nonzero(abs(turn_nn1_1-X[0])==0)
  res7.append(n_zeros/49)
  n_zeros=np.count_nonzero(abs(turn_nn2_1-X[1])==0)
  res8.append(n_zeros/49)
  n_zeros=np.count_nonzero(abs(turn_nn3_1-X[2])==0)
  res9.append(n_zeros/49)

  n_zeros=np.count_nonzero(abs(turn_nn1_2-X[0])==0)
  res10.append(n_zeros/49)
  n_zeros=np.count_nonzero(abs(turn_nn2_2-X[1])==0)
  res11.append(n_zeros/49)
  n_zeros=np.count_nonzero(abs(turn_nn3_2-X[2])==0)
  res12.append(n_zeros/49)



    

        
go_correct_percentage_10noisy1=(sum(res1)*100)/len(res1)
go_correct_percentage_20noisy1=(sum(res4)*100)/len(res4)

go_correct_percentage_10noisy2=(sum(res2)*100)/len(res2)
go_correct_percentage_20noisy2=(sum(res5)*100)/len(res5)

go_correct_percentage_10noisy3=(sum(res3)*100)/len(res3)
go_correct_percentage_20noisy3=(sum(res6)*100)/len(res6)


turn_correct_percentage_10noisy1=(sum(res7)*100)/len(res7)
turn_correct_percentage_20noisy1=(sum(res10)*100)/len(res10)

turn_correct_percentage_10noisy2=(sum(res8)*100)/len(res8)
turn_correct_percentage_20noisy2=(sum(res11)*100)/len(res11)

turn_correct_percentage_10noisy3=(sum(res9)*100)/len(res9)
turn_correct_percentage_20noisy3=(sum(res12)*100)/len(res12)



In [42]:
print("direct one : (go) \n")
print("go_correct_percentage_10noisy1:", go_correct_percentage_10noisy1 )
print("go_correct_percentage_20noisy1:", go_correct_percentage_20noisy1 )

print("go_correct_percentage_10noisy2:", go_correct_percentage_10noisy2 )
print("go_correct_percentage_20noisy2:", go_correct_percentage_20noisy2 )

print("go_correct_percentage_10noisy3:", go_correct_percentage_10noisy3)
print("go_correct_percentage_20noisy3:", go_correct_percentage_20noisy3)

print("\ndirect two : (turn) \n")

print("turn_correct_percentage_10noisy1:", turn_correct_percentage_10noisy1 )
print("turn_correct_percentage_20noisy1:", turn_correct_percentage_20noisy1 )

print("turn_correct_percentage_10noisy2:", turn_correct_percentage_10noisy2 )
print("turn_correct_percentage_20noisy2:", turn_correct_percentage_20noisy2 )

print("turn_correct_percentage_10noisy3:", turn_correct_percentage_10noisy3)
print("turn_correct_percentage_20noisy3:", turn_correct_percentage_20noisy3)

direct one : (go) 

go_correct_percentage_10noisy1: 100.0
go_correct_percentage_20noisy1: 98.96825396825396
go_correct_percentage_10noisy2: 100.0
go_correct_percentage_20noisy2: 99.68253968253968
go_correct_percentage_10noisy3: 100.0
go_correct_percentage_20noisy3: 99.42857142857143

direct two : (turn) 

turn_correct_percentage_10noisy1: 100.0
turn_correct_percentage_20noisy1: 99.02040816326529
turn_correct_percentage_10noisy2: 100.0
turn_correct_percentage_20noisy2: 99.10204081632654
turn_correct_percentage_10noisy3: 100.0
turn_correct_percentage_20noisy3: 99.83673469387755


In [31]:
W_BAM_new=np.zeros((49,63))
for i in range(4):
    W_BAM_new=W_BAM_new+product(X[i],Y[i])

In [32]:
def predict_output_BAM_new(input_vector1,input_vector2,input_vector3,input_vector4,w):
    res1=[]
    res2=[]
    res3=[]
    res4=[]
    for j in range(w.shape[1]):
        res1.append(np.dot(input_vector1,w[:,j]))
        res2.append(np.dot(input_vector2,w[:,j]))
        res3.append(np.dot(input_vector3,w[:,j]))
        res4.append(np.dot(input_vector4,w[:,j]))
        nn1=activation_function(res1)
        nn2=activation_function(res2)
        nn3=activation_function(res3)
        nn4=activation_function(res4)

    return nn1,nn2,nn3,nn4

In [35]:
predict1,predict2,predict3,predict4=predict_output_BAM_new(X[0],X[1],X[2],X[3],W_BAM_new)

print("output1:",predict1)
print("real output:",Y[0]-predict1)
print("output2:",predict2)
print("real output:",Y[1]-predict2)
print("output3:",predict3)
print("real output:",Y[2]-predict3)
print("output4:",predict4)
print("real output:",Y[3]-predict4)

output1: [1, -1, 1, -1, -1, -1, -1, 1, 1, 1, -1, -1, 1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, 1, -1, -1, 1, 1, 1, 1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, -1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, -1]
real output: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
output2: [1, -1, -1, -1, 1, 1, -1, 1, 1, -1, 1, -1, -1, 1, 1, 1, 1, -1, -1, 1, -1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, -1, 1, -1, -1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, 1, -1, -1, 1, -1, -1, 1, 1, 1, 1, -1, -1, 1]
real output: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
output3: [1, -1, -1, -1, 1, 1, 1, 1, 1, -1, -1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, -1, 1, 1, -1, 1, 1, -1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, -1, 1, 1, -1, 1, 1, 1, -1, -1, -1, -1, 1, 1, 1, -1, 1, 1, 1, -1]
real output: [0 0 0 0 0 0 0 0 0 0 0 0

In [37]:
W_inverse_new=W_BAM_new.T
predict1,predict2,predict3,predict4=predict_output_BAM_new(Y[0],Y[1],Y[2],Y[3],W_inverse_new)

print("output1:",predict1)
print("real output:",X[0]-predict1)
print("output2:",predict2)
print("real output:",X[1]-predict2)
print("output3:",predict3)
print("real output:",X[2]-predict3)
print("output4:",predict4)
print("real output:",X[3]-predict4)

output1: [1, -1, -1, -1, -1, 1, 1, 1, 1, -1, 1, 1, -1, -1, 1, 1, -1, 1, -1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, -1]
real output: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0]
output2: [1, -1, -1, 1, -1, -1, -1, 1, 1, -1, 1, -1, -1, 1, 1, 1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, 1, 1, -1, -1, 1, -1, 1, 1, 1, 1, -1, -1, 1]
real output: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0]
output3: [1, -1, -1, 1, -1, 1, 1, 1, 1, -1, -1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, -1, 1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, 1, 1, -1, -1, 1, -1]
real output: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0]
output4: [1, -1, -1, 1, -1, -1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, -1, 1, -1, -1, 1, 1, 1, 1, -1, -1, -1